language: python
python:
  - "3.4"
  - 
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
    - apt-get install python3-lxml
install:
  - pip install -r requirements.txt
# command to run tests
script: python de.py